In [3]:
%load_ext autoreload
%autoreload 2


from cn3s.model import CN3S, CN3SParams

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## CN3S class

In [5]:
params = CN3SParams()
model = CN3S(params, freq="M")

In [6]:
params

CN3SParams(name='Unnamed', area=34334.0, r0=350.0, cn_i=7.35, alfa=0.2, beta=0.00211662329536844, k0=1.0, k1=0.316, k2=0.305, act=0, warmup_steps=3)

In [7]:
model.step(287.6, [84.9, 283.2, 385.8])

prec                        287.6
past_prec    [84.9, 283.2, 385.8]
vj                       2.595722
cnv                     26.857968
s                       691.71563
q_up                    26.490301
r1                     432.510665
q_low                  131.915753
r                      300.594912
q_mm                   158.406053
q_m3s                 2098.269074
dtype: object

In [7]:
model.results

,prec,past_prec,vj,cnv,s,q_up,r1,q_low,r,q_mm,q_m3s
0,287.6,"[385.8, 283.2, 84.9]",2.6,26.919978,689.54,26.7,432.44,131.89,300.55,158.59,2100.71
1,181.6,"[287.6, 385.8, 283.2]",3.0,32.89389,518.18,10.2,354.71,108.19,246.52,118.39,1568.21
2,114.9,"[181.6, 287.6, 385.8]",2.81,30.013665,592.28,0.0,282.83,86.26,196.57,86.26,1142.61
3,103.3,"[114.9, 181.6, 287.6]",2.24,21.848639,908.54,0.0,229.21,69.91,159.3,69.91,926.04
4,3.4,"[103.3, 114.9, 181.6]",1.85,16.713709,1265.71,0.0,160.37,48.91,111.46,48.91,647.87
...,...,...,...,...,...,...,...,...,...,...,...
223,0,"[0, 15.1, 9.9]",1.05,7.560751,3105.45,0.0,49.61,15.13,34.48,15.13,200.41
224,11.7,"[0, 0, 15.1]",1.03,7.359826,3197.17,0.0,38.18,11.64,26.54,11.64,154.19
225,158.3,"[11.7, 0, 0]",1.02,7.259946,3244.65,0.0,76.56,23.35,53.21,23.35,309.3
226,179.9,"[158.3, 11.7, 0]",1.36,10.862128,2084.4,0.0,110.06,33.57,76.49,33.57,444.67
227,228.5,"[179.9, 158.3, 11.7]",1.74,15.338646,1401.95,0.0,148.7,45.35,103.35,45.35,600.71

In [51]:
_ = model.step(114.9)

In [48]:
model.results

    prec              past_prec    vj  ...       r    q_mm    q_m3s
0  287.6   [385.8, 283.2, 84.9]   2.6  ...  300.55  158.59  2100.71
1  181.6  [287.6, 385.8, 283.2]   3.0  ...  246.52  118.39  1568.21
2  114.9  [181.6, 287.6, 385.8]  2.81  ...  196.57   86.26  1142.61

[3 rows x 11 columns]

In [14]:
from utils.hydrology import Hydrology

In [16]:
hydro = Hydrology()

To sign in, use a web browser to open the page https://login.microsoft.com/device and enter the code EP2ESWDVX to authenticate.

In [59]:
q1 = hydro.get_discharge(10200000, _type="vazao")
q1

            EstacaoCodigo  NivelConsistencia    Vazao
Data
1982-11-22       10200000                  2   659.20
1982-11-23       10200000                  2   654.07
1982-11-24       10200000                  2   632.41
1982-11-25       10200000                  2   673.39
1982-11-26       10200000                  2   739.18
...                   ...                ...      ...
2025-12-26       10200000                  1  1015.41
2025-12-27       10200000                  1   912.04
2025-12-28       10200000                  1   796.08
2025-12-29       10200000                  1   743.20
2025-12-30       10200000                  1   746.55

[15376 rows x 3 columns]