# Modelo CN3S

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd

from cn3s import CN3S, CN3SParams

In [2]:
rain = pd.read_excel("../data/C20500000_CN3S.xls", header=None).iloc[9:, [0,8]]
rain = rain.rename(columns={0: "date", 8: "rain"})
rain["date"] = pd.to_datetime(rain["date"], format="%Y-%m-%d")
rain = rain.dropna()
rain = rain.set_index("date")
rain

             rain
date
1969-10-01   84.9
1969-11-01  283.2
1969-12-01  385.8
1970-01-01  287.6
1970-02-01  181.6
...           ...
1988-08-01      0
1988-09-01   11.7
1988-10-01  158.3
1988-11-01  179.9
1988-12-01  228.5

[231 rows x 1 columns]

## CN3S class

In [3]:
rain_list = rain["rain"].to_list()

In [4]:
params = CN3SParams()
model = CN3S(params)

In [5]:
params

CN3SParams(bacia='Porto Uruaçu', area=34334.0, r0=350.0, cn_i=7.35, alfa=0.2, beta=0.00211662329536844, k0=1.0, k1=0.316, k2=0.305)

In [6]:
model.run(rain_list)

Running CN3S model:   0%|          | 0/227 [00:00<?, ?step/s]

In [7]:
model.results

,prec,past_prec,vj,cnv,s,q_up,r1,q_low,r,q_mm,q_m3s
0,287.6,"[385.8, 283.2, 84.9]",2.6,26.919978,689.54,26.7,432.44,131.89,300.55,158.59,2100.71
1,181.6,"[287.6, 385.8, 283.2]",3.0,32.89389,518.18,10.2,354.71,108.19,246.52,118.39,1568.21
2,114.9,"[181.6, 287.6, 385.8]",2.81,30.013665,592.28,0.0,282.83,86.26,196.57,86.26,1142.61
3,103.3,"[114.9, 181.6, 287.6]",2.24,21.848639,908.54,0.0,229.21,69.91,159.3,69.91,926.04
4,3.4,"[103.3, 114.9, 181.6]",1.85,16.713709,1265.71,0.0,160.37,48.91,111.46,48.91,647.87
...,...,...,...,...,...,...,...,...,...,...,...
223,0,"[0, 15.1, 9.9]",1.05,7.560751,3105.45,0.0,49.61,15.13,34.48,15.13,200.41
224,11.7,"[0, 0, 15.1]",1.03,7.359826,3197.17,0.0,38.18,11.64,26.54,11.64,154.19
225,158.3,"[11.7, 0, 0]",1.02,7.259946,3244.65,0.0,76.56,23.35,53.21,23.35,309.3
226,179.9,"[158.3, 11.7, 0]",1.36,10.862128,2084.4,0.0,110.06,33.57,76.49,33.57,444.67
227,228.5,"[179.9, 158.3, 11.7]",1.74,15.338646,1401.95,0.0,148.7,45.35,103.35,45.35,600.71

In [51]:
_ = model.step(114.9)

In [48]:
model.results

    prec              past_prec    vj  ...       r    q_mm    q_m3s
0  287.6   [385.8, 283.2, 84.9]   2.6  ...  300.55  158.59  2100.71
1  181.6  [287.6, 385.8, 283.2]   3.0  ...  246.52  118.39  1568.21
2  114.9  [181.6, 287.6, 385.8]  2.81  ...  196.57   86.26  1142.61

[3 rows x 11 columns]